spring:
  application:
    name: Chatbot - API
    version: 1.1.0
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    resolve-schema-properties: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html