version: '3.8'

# run gradle bootJar to create jar file
# then run docker-compose up --scale chat-bot=3
# this will create db and 3 instances of chat-bot with nginx load balancing

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"

  chat-bot:
    build:
      context: ../../../
      dockerfile: ./support/docker/chat-bot/Dockerfile
    image: chat-bot:latest
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chatbot
#    ports:
#      - "8080:8080"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chat-bot
networks:
  default:
    name: chat-bot-network